export const theme = {
  colors: {
    background: '#171218',
    surface: '#171218',
    surfaceDim: '#171218',
    surfaceBright: '#3e373f',
    surfaceContainerLowest: '#120c13',
    surfaceContainerLow: '#1f1a21',
    surfaceContainer: '#241e25',
    surfaceContainerHigh: '#2e282f',
    surfaceContainerHighest: '#39333a',
    onSurface: '#ebdfe9',
    onSurfaceVariant: '#d1c2d2',
    inverseSurface: '#ebdfe9',
    inverseOnSurface: '#352e36',
    outline: '#9a8c9b',
    outlineVariant: '#4e4350',
    surfaceTint: '#edb1ff',
    primary: '#edb1ff',
    onPrimary: '#520070',
    primaryContainer: '#9d50bb',
    onPrimaryContainer: '#fff3fd',
    inversePrimary: '#883ca6',
    secondary: '#d6baff',
    onSecondary: '#40147a',
    secondaryContainer: '#573092',
    onSecondaryContainer: '#c7a5ff',
    tertiary: '#d0cb59',
    onTertiary: '#343200',
    tertiaryContainer: '#b4af41',
    onTertiaryContainer: '#444100',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
  },
  typography: {
    displayLg: {
      fontFamily: 'Inter',
      fontSize: 48,
      fontWeight: '700' as const,
      lineHeight: 56,
      letterSpacing: -0.96,
    },
    headlineLg: {
      fontFamily: 'Inter',
      fontSize: 32,
      fontWeight: '600' as const,
      lineHeight: 40,
      letterSpacing: -0.32,
    },
    titleLg: {
      fontFamily: 'Inter',
      fontSize: 22,
      fontWeight: '500' as const,
      lineHeight: 28,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '400' as const,
      lineHeight: 26,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    labelLg: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '600' as const,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMd: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '500' as const,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  rounded: {
    sm: 4,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
};
